### ISSUE TITLE
[Feature]: docs improvment on elpaca-process-queues and elpaca-wait

### ISSUE THREAD

**Issue by lebensterben** [progfolio/elpaca#107]
### Feature Description

I followed the example init file to bootstrap elpaca which ends with these two forms:

```elisp
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@bjorn-elpaca-order))
```

as well as set up elpaca's use-package integration with:

```elisp
(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (custom-set-variables '(elpaca-use-package-by-default t)))
(elpaca-wait)
```

And I am advised that I'll be able to use both `elpaca` or `use-package` from this point. And due to the `after-init-hook` I added, `elpaca-process-queues` is called once my `user-init-file` is loaded.

But this causes trouble for the following setup

```elisp
;; code to bootstrap elpaca is omitted
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@bjorn-elpaca-order))

(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (custom-set-variables '(elpaca-use-package-by-default t)))
(elpaca-wait)

;; above is the same as the example init file as I explained above
;; ---------------------------------------------------------------
;; below is my setup

;; This package provides `:general' keyword to `use-package'
(use-package general
  :init (require 'general))

;; this will fail as it cannot recognize the keyword `:general`
(use-package foo
  :general ("SPC" 'some-function))
```

---

My first thought is, to add a `(elpaca-process-queues)` between `(use-package general ..)` and other `use-package` forms that requires `:general`.

But it turns out that, although there is no error thrown, my theme isn't loaded correctly. So there might be other things not loaded correctly, even though there is no explicit error!

I then instead added a `(elpaca-wait)` after `(use-package general ..)`. And it now works as expected.

---

So what I'm asking now, is to clarify the difference of `elpaca-process-queues` and `elpaca-wait`.

I've no idea why calling `elpaca-process-queues` doesn't fully work here but `elpaca-wait` does, because the latter in turn calls `elpaca-process-queues`.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> I then instead added a (elpaca-wait) after (use-package general ..). And it now works as expected.

Yes. This is what you'll need to do for any package which alters something you expect to use at the top-level (e.g. use-package, elpaca-menu-functions, etc).
Taking the configuration you provided as an example:

```emacs-lisp
(elpaca elpaca-use-package
  (elpaca-use-package-mode)
  (custom-set-variables '(elpaca-use-package-by-default t)))
(elpaca-wait)
```

`elpaca-wait` processes the queue up to this point.
use-package is available.

```emacs-lisp
(use-package general :init (require 'general))

```

With `elpaca-use-package-by-default` non-nil, this form  expands to:

```emacs-lisp
(elpaca general
  (require 'general)
  (require 'general nil nil))
```

which only *queues* the package for installation.
The BODY of the macro, which requires general and adds the `:general` keyword
will not be executed until after the queue has finished processing.
Thus:

```emacs-lisp
(use-package foo :general ("SPC" 'some-function))
```

Throws an error during expansion because the :general keyword has not been installed yet.

> But it turns out that, although there is no error thrown, my theme isn't loaded correctly. So there might be other things not loaded correctly, even though there is no explicit error!

I get the following warning when running that setup:

```emacs-lisp
Error (use-package): Failed to parse package foo: use-package: Unrecognized keyword: :general
```

> So what I'm asking now, is to clarify the difference of elpaca-process-queues and elpaca-wait.

`elpaca-process-queues` processes the currently queued packages asynchronously.
`elpaca-wait` does the same, but blocks the elisp interpreter until the queues have been processed.
I suppose I could clean up the interface up by doing away with `elpaca-wait` and having `elpaca-process-queues` accept a "synchronous" argument. I didn't do that, because I wasn't sure how reliable the polling method would be when I first added it.
I've also added an additional example to the documentation which points out the need for the above.

Does that help?

**Comment by lebensterben** [comment]
> I've also added an additional example to the documentation which points out the need for the above.

Yes there is really helpful.

> I suppose I could clean up the interface up by doing away with elpaca-wait and having elpaca-process-queues accept a "synchronous" argument. I didn't do that, because I wasn't sure how reliable the polling method would be when I first added it.

I'm not very sure about this though. But your explanation on the difference between the two said functions are really important

> elpaca-process-queues processes the currently queued packages asynchronously.
elpaca-wait does the same, but blocks the elisp interpreter until the queues have been processed.

I wish they could be added to their function docstrings.

---

So my understanding is that, `elpaca` is by nature asynchronous, and this must be made more clear to users.

When using either `(elpaca ORDER)` or `(use-package PACKAGE :elpaca (ORDER))`, the order is *registered* in the queue, but not cloned or built yet.

The queued orders are registered sequentially, but the asynchronous nature means that they don't finish sequentially. Thus `elpaca-process-queues` doesn't behave as I expected, because some packages needs to be available before other packages.

`elpaca-wait` is like `await` keyword of asynchronous programming. It is a synchronous point. Though packages are still cloned and built asynchronously, but it makes sure the queue is cleaned before the Emacs lisp interpreter continues.
