### ISSUE TITLE
elpaca and :defered t

### ISSUE THREAD

**Issue by ashton314** [progfolio/elpaca#11]
Hi there,

While trying elpaca out, I noticed a lot of my packages were not loading when expected. E.g. magit would get installed, but when I'd hit `C-x g` with this config I would get an error saying that `magit-status` was not defined:

```emacs-lisp
(elpaca-use-package magit
  :defer t
  :bind (("C-x g" . 'magit-status)
         ("s-g" . 'magit-status)))
```

Removing the `:defer t` makes it work; I did that will all my packages an my Emacs load time is somewhere between 3 and 5 seconds, which is pretty slow. (Though, oddly enough, `emacs-init-time` doesn't report this lag before Emacs becomes usable; is there a better way to clock whatever is going on during elpaca's init?)

Is there something I'm doing wrong? Or is elpaca not able to handle the `:defer` keyword and the lazy-loading properly?

**Comment by progfolio** [comment]
`elpaca-use-package' is a very simple wrapper of `use-package'.
Let's take a look at the expansion:

```emacs-lisp
(elpaca-use-package magit
  :defer t
  :bind (("C-x g" . 'magit-status)
         ("s-g" . 'magit-status)))
```

Expands to:

```emacs-lisp
(elpaca magit
  (use-package magit :defer t :bind
    (("C-x g" quote magit-status)
     ("s-g" quote magit-status))))
```

Note the `quote` symbols. That doesn't look right to me.
I don't use `:bind`, but perhaps the commands shouldn't be quoted?
e.g.

```emacs-lisp
(use-package magit
  :defer t
  :bind (("C-x g" . magit-status) ;no quote
         ("s-g" . magit-status))) ;no quote
```

Expands to:

```emacs-lisp
(progn
  (unless
      (fboundp 'magit-status)
    (autoload
      (function magit-status)
      "magit" nil t))
  (bind-keys :package magit
             ("C-x g" . magit-status)
             ("s-g" . magit-status)))
```

which autoloads those commands. That looks correct to me.

> I did that will all my packages an my Emacs load time is somewhere between 3 and 5 seconds, which is pretty slow.

I would expect as much if all packages are being loaded up front.
You'll definitely want to make use of lazy loading as much as possible for a fast init time.
That's not Elpaca specific, though.

> emacs-init-time doesn't report this lag before Emacs becomes usable; is there a better way to clock whatever is going on during elpaca's init?

Elpaca's queue is built during the initialization, it is processed during `after-init-hook` via `elpaca-process-queues` (added in the second to last line of the bootstrap snippet).
That's why the time reported by `emacs-init-time` doesn't reflect the time it took to process the queues. You could add something like the following to `elpaca-after-init-hook`:

```emacs-lisp
(add-hook 'elpaca-after-init-hook
          (lambda ()
            (message "Emacs loaded in %s with %d garbage collections."
                     (format "%.2f seconds"
                             (float-time
                              (time-subtract (current-time) before-init-time)))
                     gcs-done)))
```


Does that help?

**Comment by progfolio** [comment]
Took a look at https://github.com/jwiegley/use-package#key-binding
It does look like the quoted symbols are not the correct syntax.

**Comment by ashton314** [comment]
And yet the malformed syntax worked for so long… 🤷🏼‍♂️  Sheesh, that's odd. Thanks for such a detailed explanation! Things are working much better now.

Load is way snappier now: I haven't had a chance to try out your timing hook, but I'll give it a whirl later this week.

Thank you again for the pointers and help. :)
