### ISSUE TITLE
[Support]: Document using elpaca-wait  to block until after-init

### ISSUE THREAD

**Issue by belak** [progfolio/elpaca#116]
### Elpaca Version

ec7b71b HEAD

### Operating System

MacOS

### Description

I'm migrating to elpaca from straight and I was surprised to see that multiple use-package blocks didn't work as expected because elpaca runs asynchronously during after-init, so many after-init hooks weren't set up before after-init was running.

I realize the documentation says you can use `elpaca-after-init` but that only works if you have control over the code which sets up the hook. I ran into this with the `dashboard` package which has you call `(dashboard-setup-startup-hook)` in your config block which sets up multiple things to be called.

The easiest way around this I've found is to call (elpaca-wait) as the last thing in your init.el rather than letting elpaca run everything during after-init - maybe it would be worth mentioning as a last resort?

**Comment by progfolio** [comment]
Thanks for the suggestion.
Another user had a similar issue with dashboard and company-tng:

https://github.com/progfolio/elpaca/issues/91

I'll have to think on whether or not I want to recommend this explicitly.
My hesitation is that it may lead to `elpaca-after-init-hook` being run after it is supposed to be.
We can't assume a queue is the last queue if we're waiting on it (there may be more after polling is finished), so `elpaca-after-init` time is not set. There are other checks in place which should prevent `elpaca-after-init-hook` from being run, but I'll have to review them to see if it's enough.

I would also consider this a bug in dashboard's case:

[Instead of adding a lambda](https://github.com/emacs-dashboard/emacs-dashboard/blob/b648a45684677aa29cdb00e4d14d02dd9fa9cb68/dashboard.el#L456-L469)

Adding a lambda function to a hook is generally discouraged because it makes it difficult to remove the hook later.
If the functions there were properly defined, there could be another function which added them to the hook (e.g. `dashboard-configure`). This would also allow one to call that function when they wanted (e.g. during `elpaca-after-init-hook`).

**Comment by progfolio** [comment]
For now, I've documented the workaround in the wiki:

https://github.com/progfolio/elpaca/wiki/after-init-hook%3F-emacs-startup-hook%3F

**Comment by progfolio** [comment]
FYI @belak: I've submitted a couple patches to emacs-dashboard to make it so you can avoid calling elpaca-wait to set it up. See: https://github.com/emacs-dashboard/emacs-dashboard#open-the-dashboard
