### ISSUE TITLE
[Bug]: Can't install nano-emacs without errors (or weird config)

### ISSUE THREAD

**Issue by philipsd6** [progfolio/elpaca#138]
### Elpaca Version

    Elpaca 3c6dc41 HEAD -> master, origin/master, origin/HEAD
    installer:      0.4
    emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-05-28
    git --version:  git version 2.40.1

### Operating System

Ubuntu 22.04.2 LTS

### Description

The [Nano-Emacs](https://github.com/rougier/nano-emacs/) project provides a bunch of `.el` files to setup the environment/theme according to the users desires. The expectation is to use it like this:

```elisp
(elpaca-test
  :dir "elpaca.test"
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package nano-emacs
    :elpaca (:host github :repo "rougier/nano-emacs")
    :config
    ;; require mandatory files and whatever else is desired
    (require 'nano-base-colors)
    (require 'nano-faces)
    (require 'nano-theme)
    (require 'nano-theme-dark)
    (nano-theme-set-dark)
    (nano-faces)
    (nano-theme))
  )
```
This form results in `Error (use-package): Cannot load nano-emacs` because there is no `nano-emacs.el` to load. There *is* a `nano.el` sample configuration, so changing the form to:
```elisp
(use-package nano
    :elpaca (:host github :repo "rougier/nano-emacs")
```
&hellip;works... but I don't want to load the sample config, I want to use my own as above. The only thing I've been able to do that "works" is this, but it seems hackish and ugly:
```elisp
(elpaca-test
  :dir "elpaca.test"
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package nano-base-colors  ;; ugh
    :elpaca (:host github :repo "rougier/nano-emacs")
    :config
    (require 'nano-faces)
    (require 'nano-theme)
    (require 'nano-theme-dark)
    (nano-theme-set-dark)
    (nano-faces)
    (nano-theme))
  )
```
What I would prefer is some way to pull the repo, build into the usual build dir, but do not try to load anything so I can require files myself in the `:config` block. I was able to do this with straight, but I can't find a way to do this with elpaca.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a thorough report.
I believe the core of the problem is the fact that nano-emacs does not provide a named feature "nano-emacs". It looks like nano.el provides the feature "nano".  `use-package` (which would've been more aptly named "use-feature", but that ship has sailed) wants the feature name as its first argument.

It also seems odd to me that you would have to explicitly require sub-features of the package. If everything is set up correctly, autoloads should take care of that. I'm not familiar  enough with the package, but does this do work as expected? I get no errors and the dark theme seems like it is enabled on my end:

```emacs-lisp
(elpaca-test
  :dir "elpaca.test"
  :init
  (elpaca elpaca-use-package
    (elpaca-use-package-mode)
    (setq elpaca-use-package-by-default t))
  (elpaca-wait)

  (use-package nano ;; <- Main feature name here.
    ;; Item name as advertised by menus in recipe below.
    :elpaca (nano-emacs :host github :repo "rougier/nano-emacs")
    :config
    (nano-theme-set-dark)
    (nano-faces)
    (nano-theme)))
```

**Comment by progfolio** [comment]
> No, as I said above, since there is a nano.el in the repo, using that as the feature name works, but it loads the undesired sample config (for one thing, it sets a layout, which I don't want to use.)

Apologies. I misunderstood the purpose of nano.el. I thought it provided the "core" features of the package, not a demo configuration (A better name would probably be nano-demo.el, but that's up to the package author).

> In my previous config I was using straight and this was working there
>And that worked fine, no errors; and since straight wasn't working asynchronously, I could just do my requires and function calls under that.

The straight.el test case below signals the same error:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "straight.nano-emacs"
  :post-bootstrap 
  (use-package nano-emacs :straight
    (:type git :host github :repo "rougier/nano-emacs")
    :custom
    (nano-font-family-monospaced "Roboto Mono")
    (nano-font-family-proportional "DejaVu Sans")
    (nano-font-size 14)))
```
</details>

- Test run at: `2023-05-30 13:19:33`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD) 1605691 2023-05-23`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-05-20`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 4701c9a 2023-05-25
Cloning nano-emacs...
Cloning nano-emacs...done
Building nano-emacs...
Building nano-emacs...done

Error (use-package): Cannot load nano-emacs

Packages:
"straight"                n/a                  develop 4701c9a 2023-05-25
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 5b7f066a 2023-05-29
"gnu-elpa-mirror"         n/a                  master c89a389 2023-05-19
"nongnu-elpa"             n/a                  main 4456edc 2023-05-24
"el-get"                  melpa                master 46be7740 2023-05-14
"emacsmirror-mirror"      n/a                  master e9774fe 2023-05-22
"nano-emacs"              n/a                  master 086bbe7 2023-03-17


```
</details>

Straight's use-package integration will effectively expand to:

```emacs-lisp
(progn
  (straight-use-package '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))
  ;; use-package may convert this error to a warning
  ;; depending on value of `use-package-expand-minimally'.
  (require 'nano-emacs nil t)
  ;; Additional config omitted.
  )
```

So I would expect `(use-package 'nano-emacs)` to fail as it does above.
You'll want to find the appropriate feature name (if nano provides one) which loads what you want to.
(maybe `nano-theme`? I'm not familiar enough with the package to say for sure). If there isn't one, I would raise that issue upstream with nano-emacs. They could provide a "nano-core" named feature, or something similar. I don't think the error has anything to do with Elpaca or Straight, though. If you have more info which indicates otherwise, let me know and I'll look into it more.

**Comment by progfolio** [comment]
I simplified the expansion for the purpose of illustration.
Here's the actual expansion via straight's use-package integration with `use-package-expand-minimally nil`:

```emacs-lisp
(progn
  (straight-use-package 'nano-emacs)
  (defvar use-package--warning3
    #'(lambda
	(keyword err)
	(letq
	    ((msg
	      (format "%s/%s: %s" 'nano-emacs keyword
		      (error-message-string err))))
	  (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (if
	  (not
	   (require 'nano-emacs nil t))
	  (display-warning 'use-package
			   (format "Cannot load %s" 'nano-emacs)
			   :error))
    (error
     (funcall use-package--warning3 :catch err))))
```

**Comment by philipsd6** [comment]
Oh, I see... thanks for the clarification. I'm not sure why I wasn't getting any errors in my previous config with straight, but it's clear this is something that should be handled at a different level. Thanks!
