### ISSUE TITLE
[Bug]: Am I getting throttled?

### ISSUE THREAD

**Issue by ashton314** [progfolio/elpaca#163]
### Elpaca Version

```
Elpaca 6df9652 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.0.92 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4.1 (Build 22F82))
 of 2023-07-05
git --version:  git version 2.39.2
```

### Operating System

macOS

### Description

I'm having a hard time running `elpaca-update-all`:
<img width="1341" alt="image" src="https://github.com/progfolio/elpaca/assets/2874507/a7b571ab-ba5f-4536-9999-0437c276d105">

I can clone and individually update all those packages. Could there be some throttling going on from GitHub's side? Or is this likely an Elpaca issue? It started just today, and I try to keep Elpaca pretty up-to-date.

**Comment by progfolio** [comment]
Duplicate of: https://github.com/progfolio/elpaca/issues/156

A few people have hit this issue lately. Likely Github's API.
Setting `elpaca-queue-limit` should help with this. I left the default value nil, but I'm reconsidering in light of this issue cropping up for several people. I personally have it set to 30, which actually sped up my initial install (probably due to the main Emacs thread not being flooded by subprocesses). I've yet to hit any Github API limits, too.

**Comment by ashton314** [comment]
Set `(defvar elpaca-queue-limit 10)` in my setup; all seems to be working again. Maybe my IP block was throttled or GitHub was having a bad day 🤷🏼‍♂️ 

Thanks for the tips!

**Comment by progfolio** [comment]
Glad to hear it's working again. Thanks
