### ISSUE TITLE
[Support]: Org Version Mismatch

### ISSUE THREAD

**Issue by x61** [progfolio/elpaca#166]
### Elpaca Version

Elpaca b40afe0 HEAD -> master
installer:      0.4
emacs-version:  GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a))
 of 2023-05-11
git --version:  git version 2.39.2 (Apple Git-143)

### Operating System

Mac OS

### Description

I have successfully installed org with `use-package org` command inside my configuration file but each time I load up the config, I get  an error. It loads if I remove the updated org mode and use the and  that came with my version of emacs. 

`(error "Org version mismatch.  Make sure that correct ‘load-path’ is set early in init.el")`

**Comment by progfolio** [comment]
That error is usually signaled when the built-in org mode is loaded before another version is loaded. Do you have a link to your init file?

**Comment by x61** [comment]
Yeah, I am loading the orgConfig in the init.el file. How would I load it? Here is what is in my init file and nothing else.

`(org-babel-load-file  "~/.emacs.d/orgConfig.org")`

**Comment by progfolio** [comment]
> Yeah, I am loading the orgConfig in the init.el file. How would I load it? Here
> is what is in my init file and nothing else.
> 
> `(org-babel-load-file "~/.emacs.d/orgConfig.org")`
> 
> Any recommendation on how to avoid loading org-babel-load-file in the init?

I recommend tangling your init.el from the Org file.
This will allow your init file to load without loading Org.
It should also decrease your Emacs startup time.
The downside is that you will need to re-tangle this Org file when you change it.
However, a file-local hook can be added to after-save-hook, so that the file is automatically tangled when saved.
I do something similar for my init files:

https://github.com/progfolio/.emacs.d/


I don't track the tangled init.el in version control, just the Org file. There's a "tangle-init" init bash script in there, too, that can be used from the command line to initially tangle the init file from a fresh clone.

Another approach would be to move the code to install Elpaca and Org into init.el, and *then* `org-babel-load-file` the Org file.

It's up to you how to approach it, but the root of the problem is that the built-in Org version is loaded prior to the requested version.

**Comment by x61** [comment]
Thank you. I updated my init.el file to load the tangled version of my config and asked to have org installed in my config file. I also have it automatically tangled as shown in the screenshot below.
<img width="535" alt="image" src="https://github.com/progfolio/elpaca/assets/6430853/a2844bf4-3655-4c91-bb8d-dcd964422dd5">
The issue is that if I make change to the org file and it gets tangled and I wanted to reload the tangled *.el file, I elpaca hangs on `org` and I am getting an error as shown below. It runs fine if I restart emacs and so long as I do not try to load-file *.el (tangled file). 
<img width="1718" alt="image" src="https://github.com/progfolio/elpaca/assets/6430853/8dd9d33a-79d4-4ebc-91b1-84f0befd1941">

**Comment by progfolio** [comment]
please share your config and the full text of the backtrace (an image won't do).
