### ISSUE TITLE
[Bug]: nano-emacs elpaca--dependencies error

### ISSUE THREAD

**Issue by shassard** [progfolio/elpaca#178]
### Elpaca Version

Elpaca e66733b HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
git --version:  git version 2.41.0

### Operating System

nixos unstable

### Description

After updating elpaca to e66733b, I'm observing a failure for `nano-emacs` to load internal symbols that previously worked.

The commit in question:
https://github.com/progfolio/elpaca/commit/e66733bbfef38ff8ea6f6c293cd64e547c0ceb99

The error:
```
elpaca--dependencies: "nano-writer.el" Package-Requires error: (file-missing "Opening input file" "No such file or directory" "/home/stephen/.config/emacs/elpaca/repos/elpaca/nano-writer.el")
```

The `nano-emacs` recipe:
```
(elpaca '(nano-emacs :type git :host github :repo "rougier/nano-emacs")
  (require 'nano-base-colors)
  (require 'nano-faces)
  (require 'nano-defaults)
  (require 'nano-bindings))
```

`nano-writer.el`'s path:
https://github.com/rougier/nano-emacs/blob/master/nano-writer.el

Reverting this commit and restarting emacs, followed by an `elpaca-rebuild` of `nano-emacs` resolves the issue.

**Comment by progfolio** [comment]
> ### Elpaca Version
> 
> Elpaca e66733b HEAD -> master, origin/master, origin/HEAD installer: 0.5 emacs-version:
> GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
> git --version: git version 2.41.0
> 
> 
> ### Operating System
> 
> nixos unstable
> 
> ### Description
> 
> After updating elpaca to e66733b, I'm observing a failure for `nano-emacs` to load
> internal symbols that previously worked.
> 
> The commit in question:
> https://github.com/progfolio/elpaca/commit/e66733bbfef38ff8ea6f6c293cd64e547c0ceb99
> 
> The error:
> ```
> elpaca--dependencies: "nano-writer.el" Package-Requires error: (file-missing "Opening input file" "No such file or directory" "/home/stephen/.config/emacs/elpaca/repos/elpaca/nano-writer.el")
> ```
> 
> The `nano-emacs` recipe:
> ```
> (elpaca '(nano-emacs :type git :host github :repo "rougier/nano-emacs")
>   (require 'nano-base-colors)
>   (require 'nano-faces)
>   (require 'nano-defaults)
>   (require 'nano-bindings))
> ```
> 
> `nano-writer.el`'s path: https://github.com/rougier/nano-emacs/blob/master/nano-writer.el
> 
> Reverting this commit and restarting emacs, followed by an `elpaca-rebuild` of
> `nano-emacs` resolves the issue.

Thanks for the report.
There are a couple of issues at play here.
First, e777eeb did introduce a bug where the value of default-directory was not being set in the recycled buffer where package dependencies are parsed.
I've corrected that on the master branch. See the following test case:


<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init (setq elpaca-menu-functions '(elpaca-menu-melpa))
  :init (elpaca '(nano-emacs :type git :host github :repo "rougier/nano-emacs")
          (require 'nano-base-colors)
          (require 'nano-faces)
          (require 'nano-defaults)
          (require 'nano-bindings))
  (elpaca-wait)
  (elpaca-test-log "#unique"))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>270c287 HEAD -> master, origin/master, origin/HEAD, fix/deps</td>
<tr><td>isntaller</td><td>0.5</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-08-18</td>
<tr><td>git</td><td>git version 2.42.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.ASOQfO/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.ASOQfO/elpaca/repos/elpaca...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.ASOQfO/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
elpaca-log: "#unique"
"
elpaca                         finished             ✓ 0.647 secs                                                                     03.369330
nano-emacs                     finished             ✓ 1.212 secs                                                                     03.935278
"

 Test Env

Elpaca 270c287 HEAD -> master, origin/master, origin/HEAD
installer:      0.5
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
 of 2023-08-18
git --version:  git version 2.42.0
```
</details>

There's also an issue with the nano-emacs recipe.
The `ITEM` in the declaration's order is used as the package name, which is used to determine the "main" elisp file. This is important for determining a package's dependencies.
`nano-emacs` will not match any files in the repository.
The last of the fallback heuristics checks the first ".el" file it can find in the repo.
In this case, "nano-agenda.el" doesn't declare Package-Requires metadata, so the package is determined to have no dependencies.
It's a happy accident that it works.
If nano adds any external dependencies, that recipe will not work for Elpaca or straight.el.
I suggest opening a bug upstream with nano-emacs to ask them to change the installation instructions so the recipe identifies the package as "nano" instead of "nano-emacs". e.g.:

``` emacs-lisp
(elpaca (nano :host github :repo "rougier/nano-emacs"))
;;or
(straight-use-package '(nano :type git :host github :repo "rougier/nano-emacs"))
```

Elpaca has the `:main` recipe keyword, which could be added to explicitly tell it where to look for a dependency declaration, but straight.el has no such feature.

Related: #138

Thanks again and let me know if you run into any issues after updating.

**Comment by shassard** [comment]
Thanks! That worked perfectly. I've PR'd the `nano-emacs` repo with the recommended fix. Thanks for the super quick response.

**Comment by progfolio** [comment]
Thank you for following through with the upstream and testing.
