### ISSUE TITLE
[Bug]: Auctex version doesn't include its version number, only the commit hash

### ISSUE THREAD

**Issue by hankertrix** [progfolio/elpaca#217]
### Elpaca Version

Elpaca 6e04e15 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
git --version:  git version 2.43.0

### Operating System

Arch Linux

### Description

![image](https://github.com/progfolio/elpaca/assets/91734413/1cb49e96-d7a9-483a-9412-c03a86dc333c)

Auctex should have a version number alongside its commit hash like other packages, as shown below:
![image](https://github.com/progfolio/elpaca/assets/91734413/77d50ea2-7c4f-4b9d-9ce9-908405e67ab3)

I'm not sure if this is an issue with Elpaca or with Auctex, but it seems to have happened after this bunch of commits to Auctex:
![image](https://github.com/progfolio/elpaca/assets/91734413/ec78288a-3a08-4eb1-aa3c-5b9fa918f135)

And all of the commits after 9th December for Elpaca.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.
[Please prefer text to screenshots for text info in the future](https://github.com/progfolio/elpaca/wiki/Troubleshooting#prefer-screenshots-when-sharing-text).

The reason the version for Auctex doesn't show in the `elpaca-info` buffer is because Auctex does not define its version in a standard way. Instead of declaring it in the package header metadata with a `Package-Version` or `Version` field, or a -pkg.el file, it is generated by Make at installation time and hardcoded in tex-site.el (see the `AUCTex-version` constant).
They could use the same technique to bake the version into a standard location elisp package managers look for (perhaps that's worth raising an issue upstream for if you're interested). Unfortunately, there's not much I can do on Elpaca's side.

The commit should still be useful enough if you need to provide the AucTex maintainers with the version you're on, though.

**Comment by hankertrix** [comment]
I see, the reason I'm raising this issue is because the package version comparison doesn't work properly when trying to install evil-tex. Evil-tex fails to install with the reason being that it requires auctex >= 11.88, but the latest git commit of auctex is far past auctex version 11.88.

This used to work properly before the commits mentioned above and I can't figure out where the issue originated from.

**Comment by progfolio** [comment]
> I see, the reason I'm raising this issue is because the package version
> comparison doesn't work properly when trying to install evil-tex.

Please start with the reason you're asking instead of a second-order question when creating an issue.
That will save us both time in the future.

> This used to work properly before the commits mentioned above and I can't figure
> out where the issue originated from.

Checking package version constraints was added to Elpaca in commit 85bfd9843327801ef07afc435434da3df0a1895c .

In general, when updating packages, I recommend running `elpaca-fetch` or `elpaca-fetch-all` to download the changes before merging them. That should give you an elpaca-log buffer with the search query set to `#latest #update-log` which will allow you to inspect changes before merging them in. This currently the best way to get a changelog for Elpaca.

> Evil-tex fails to install with the reason being that it requires auctex >=
> 11.88, but the latest git commit of auctex is far past auctex version 11.88.

That's because auctex chooses to convey their version information in a non-standard way.
It's generated by the Make script and embedded directly into tex-site.el.
I've added a way to workaround such packages.
See the test case below:

<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init
  (setq elpaca-menu-functions '(elpaca-menu-gnu-devel-elpa elpaca-menu-melpa))
  :init
  (elpaca (auctex :build (:not elpaca--compile-info)
                  :pre-build (("./autogen.sh")
                              ("./configure"
                               "--without-texmf-dir"
                               "--with-packagelispdir=./"
                               "--with-packagedatadir=./")
                              ("make"))
                  :files ("*.el" "doc/*.info*" "etc" "images" "latex" "style")
                  :version (lambda (_) (require 'tex-site) AUCTeX-version)))
  (elpaca evil-tex)
  (elpaca-wait)
  (elpaca-test-log "#unique")
  (message "auctex version: %S" (elpaca--declared-version (elpaca-get 'auctex))))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>f4d5267 HEAD -> master, origin/master, origin/HEAD</td>
<tr><td>isntaller</td><td>0.6</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-12-18</td>
<tr><td>git</td><td>git version 2.43.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.AipGda/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.AipGda/elpaca/repos/elpaca...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.AipGda/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/doc/init.el...
Checking /tmp/elpaca.AipGda/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.AipGda/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.AipGda/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.AipGda/elpaca/repos/elpaca/test/elpaca-test.el...
Done (Total of 11 files compiled, 3 skipped in 4 directories)

Downloading GNU-devel ELPA...
Downloading MELPA recipes...
Downloading MELPA recipes...100%
elpaca-log: "#unique"
"
elpaca   finished ✓ 0.583  secs  04.649775
goto-chg finished ✓ 0.614  secs  05.540218
evil     finished ✓ 2.125  secs  06.610289
auctex   finished ✓ 20.395 secs  24.515906
evil-tex finished ✓ 21.629 secs  25.695905
"
auctex version: "13.2"

 Test Env

Elpaca f4d5267 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
 of 2023-12-18
git --version:  git version 2.43.0
```
</details>

Try adding the `:version` function in the test case to your auctex recipe, upgrading Elpaca, then re-installing auctex and evil-tex.
Should work on the current master branch. Testing is appreciated.

**Comment by hankertrix** [comment]
> Please start with the reason you're asking instead of a second-order question when creating an issue.
That will save us both time in the future.

Sure thing, I'll do that in the future.

> Checking package version constraints was added to Elpaca in commit 85bfd98 .

> In general, when updating packages, I recommend running elpaca-fetch or elpaca-fetch-all to download the changes before merging them. That should give you an elpaca-log buffer with the search query set to #latest #update-log which will allow you to inspect changes before merging them in. This currently the best way to get a changelog for Elpaca.

I see, I'll do that in the future, thanks!

> I've added a way to workaround such packages.

Thank you so much! The given solution works perfectly and I can install evil-tex without any issues.

**Comment by progfolio** [comment]
Glad to hear it's working. Thanks for testing.
