### ISSUE TITLE
[Support]: Unable to determine elpaca-core-date

### ISSUE THREAD

**Issue by Icy-Thought** [progfolio/elpaca#222]
### Elpaca Version

Elpaca f752db6 HEAD -> master, origin/master, origin/HEAD
installer:      0.6
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0)
git --version:  git version 2.42.0

### Operating System

Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231222.6df37dc

### Description

```lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p ((emacs "Unable to determine elpaca--core-date" nil nil)))
  version-list-<((((emacs "Unable to determine elpaca--core-date" nil nil))) (20231204))
```

Emacs is unable to load my config properly because of `git-commit` inability to be updated (`elpaca--core-date`), which is caused by my use of Emacs built from the master branch. And I think the cause for this issue lies within `elpaca.el` lack of support for master branch versions of Emacs.

https://github.com/progfolio/elpaca/blob/f752db6d28a633f3328eb9fd4f2e24b927f2e812/elpaca.el#L1106-L1111

Therefore I thought I should ask if there is a plan to support master branch versions of Emacs or not

**Comment by progfolio** [comment]
> [Is there] a plan to support [Emacs] master branch?

Yes. I use the master branch myself.

I recently added dependency version constraint checks to Elpaca: 85bfd9843327801ef07afc435434da3df0a1895c

The core date is a `YYYYMMDD` format version for all of the bundled, or core, elisp shipped with Emacs. 
Elpaca is able to figure this out for stable releases and uses `emacs-build-time` when it is available (for people actively developing core packages). When users are not on a stable release and `emacs-build-time` is not set, the variable will need to be manually set.

The reason this variable is needed in the first place is an unfortunate side effect of the current state of elisp versioning. Rather than agree on a single versioning scheme, several incompatible schemes have developed over time. MELPA versions packages with a `YYYYMMDD` date-based format, and a handful of packages (git-commit in your case) declare minimum required dependency versions in that style.
The core date is a "best guess" way of dealing with this inconsistency.

> ```lisp
> Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p ((emacs "Unable to determine elpaca--core-date" nil nil)))
>   version-list-<((((emacs "Unable to determine elpaca--core-date" nil nil))) (20231204))
> ```

This should be taken care of via 5657f92.
A warning will be displayed when it is unable to be determined automatically.
In those cases the `elpaca-core-date` variable should be set prior to packages being queued.
e.g.

``` emacs-lisp
(setq elpaca-core-date "20231228") ;; set to the build date of Emacs
```

That date will be used when a package depends on a built-in package, requesting a minimum version in MELPA version date-based schema.

Does that help?

**Comment by Icy-Thought** [comment]
> Rather than agree on a single versioning scheme, several incompatible schemes have developed over time.
Oh, that is rather unfortunate.

> Does that help?
Yes it does! Thank you for taking the time to explain the situation to me! I'll add `(setq elpaca-core-date "YYYYMMDD")` to my Emacs setup.

**Comment by progfolio** [comment]
Glad to hear it. Thanks for taking the time to fill out a ticket.

**Comment by progfolio** [comment]
Just for curiosity's sake, what is the value of the `source-directory` variable on your version of Emacs? I expect to be nil, but if it's non-nil, I may be able to automate the `elpaca-core-date` variable in your case.

**Comment by Icy-Thought** [comment]
`C-h v source-directory` returns `Its value is "/build/source/".`

**Comment by Icy-Thought** [comment]
Also, adding `(setq elpaca-core-date "20231211")` prior to `elpaca-wait` in the bootstrap process yields `elpaca--check-version: (wrong-type-argument listp "20231211")`.

**Comment by progfolio** [comment]
> adding (setq elpaca-core-date "20231211") prior to elpaca-wait in my bootstrap process yields elpaca--check-version: (wrong-type-argument listp "20231211")

Apologies, it should be `(setq elpaca-core-date '(20231211))`.

> C-h v source-directory returns Its value is "/build/source/".

I'm not familiar with NixOS. Does the following return non-nil?:

```emacs-lisp
(when-let (((file-exists-p source-directory))
           (default-directory source-directory))
  (elpaca-process-call "git" "log" "-n" "1" "--format=%cd" "--date=format:%Y%m%d.%s"))
```

**Comment by Icy-Thought** [comment]
Evaluating that function by copy-pasting returns nothing, but when I supply the `elpaca-process-call` to `eval-expression` for the last line only I get `(0 "20231228.1703776929" nil)`

**Comment by progfolio** [comment]
It would need to be non-nil for the whole expression.
Unfortunately, it doesn't look like that method will work with NixOS.
Manually setting `elpaca-core-date` will have to do for now.

**Comment by Icy-Thought** [comment]
Oh, that's unfortunate. Nonetheless, appreciate the help! :)

**Comment by montchr** [comment]
FWIW I am running into this on Emacs 21.1.90 on NixOS. `emacs-build-time` is nil.

I wonder if this is specific to Nix the package manager (not NixOS). That might be determined by finding out if users on other Linux distros or macOS see the same issue.

**Comment by progfolio** [comment]
>  Emacs 21.1.90 

Elpaca requires a minimum version of Emacs 27.1.
I have no plans of supporting versions dating as far back as 21.

**Comment by montchr** [comment]
Ack! I meant 29.1.90!

**Comment by progfolio** [comment]
Ah, that makes much more sense.
See https://www.gnu.org/software/emacs/manual/html_node/efaq/Latest-version-of-Emacs.html for info on Emacs versioning scheme. The version you are on is a development version. You'll want to set the `elpaca-core-date` manually.

**Comment by montchr** [comment]
Sorry to keep on with this closed issue, though I am following the above advice as closely as I can and finding that the warning still appears.

I've set `elpaca-core-date` to the suggested value of `'(20231211)` and alternatively `'(20231019)`, based on the tagging of 29.1.90 [\[source\]](https://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-29.1.90):

```elisp
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t)
  ;; See <https://github.com/progfolio/elpaca/issues/222>
  (setq elpaca-core-date '(20231211))
  ;; <https://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-29.1.90>
  ;; (setq elpaca-core-date '(20231019))
  )
```

Looking at the source for `elpaca--core-date`, I see the following expression:

```elisp
(alist-get emacs-version '(("27.1" . 20200804) ("27.2" . 20210319) ("28.1" . 20220403)
                                       ("28.2" . 20220912) ("29.1" . 20230730))
                       nil nil #'equal)
```

So, when evalled, that expression returns nil. 

FWIW I can confirm I have the latest commit from Elpaca.

At this point I'm pretty confused, so I'll probably just make sure I have the stable version of Emacs (because I hadn't intended to be on the development version anyway -- that was a mistake).

**Comment by progfolio** [comment]
> ```emacs-lisp
>   (setq elpaca-core-date '(20231211))
> ```

Move this before the installer script.
It needs to be set before elpaca.el is loaded.

**Comment by Icy-Thought** [comment]
@montchr I personally am installing `emacs-git` from the [emacs-overlay](https://github.com/nix-community/emacs-overlay) and to find out what build version I am using I just execute `emacs-build-description` and look for the `--prefix=/nix/store/...-emacs-git-20YYMMDD`. In my case the value happened to be `20231211`, thus I added it prior to the first instance of `(elpaca-wait)` in my Emacs config.

**Comment by mplanchard** [comment]
There is probably a better way to do this, but I came up with this to collect and use the value automatically, so I don't have to worry about updating it when I update emacs:

```lisp
;; Return whether we're running on NixOS
(defun my/nixos-p ()
  (let ((sysinfo (shell-command-to-string "uname -v")))
    (not (eq (cl-search "NixOS" sysinfo) nil))))

;; A function to retrieve the build date of emacs, needed for elpaca on NixOS
(defun my/nixos/get-emacs-build-date ()
  (string-match "--prefix.*emacs.*\\([[:digit:]]\\{8\\}\\)" system-configuration-options)
  (let ((config-date (match-string 1 system-configuration-options)))
    (car (read-from-string config-date))))

;; Run this before elpaca code
(if (my/nixos-p)
    (setq elpaca-core-date (list (my/nixos/get-emacs-build-date))))
```

**Comment by progfolio** [comment]
> There is probably a better way to do this, but I came up with this to collect and use the value automatically, so I don't have to worry about updating it when I update emacs:
> 
> ```commonlisp
> ;; Return whether we're running on NixOS
> (defun my/nixos-p ()
>   (let ((sysinfo (shell-command-to-string "uname -v")))
>     (not (eq (cl-search "NixOS" sysinfo) nil))))
> 
> ;; A function to retrieve the build date of emacs, needed for elpaca on NixOS
> (defun my/nixos/get-emacs-build-date ()
>   (string-match "--prefix.*emacs.*\\([[:digit:]]\\{8\\}\\)" system-configuration-options)
>   (let ((config-date (match-string 1 system-configuration-options)))
>     (car (read-from-string config-date))))
> 
> ;; Run this before elpaca code
> (if (my/nixos-p)
>     (setq elpaca-core-date (list (my/nixos/get-emacs-build-date))))
> ```

Thank you. If you think this could be useful for other Nix users,
feel free to add it to the wiki:

https://github.com/progfolio/elpaca/wiki/Usage-with-Nix

I think you could simplify your nixos-p predicate as follows:

```emacs-lisp
(defun my/nixos-p ()
  "Return t if operating system is NixOS, nil otherwise."
  (string-match-p "NixOS" (shell-command-to-string "uname -v")))
```

Might be better to use `string-to-number` instead of `read-from-string` here.
It will avoid the need to call `car` on the result.

```emacs-lisp
(defun my/nixos/get-emacs-build-date ()
  "Return NixOS Emacs build date."
  (string-match "--prefix.*emacs.*\\([[:digit:]]\\{8\\}\\)" system-configuration-options)
  (string-to-number (match-string 1 system-configuration-options)))
```

`when` is appropriate here since there is no consequent branch:

```emacs-lisp
;; Run this before the elpaca.el is loaded. Before the installer in your init.el is a good spot.
(when (my/nixos-p) (setq elpaca-core-date (list (my/nixos/get-emacs-build-date))))
```

**Comment by hankertrix** [comment]
Emacs 29.4 is a new stable release that needs to be added.

https://github.com/progfolio/elpaca/blob/master/elpaca.el#L1215-L1217

**Comment by progfolio** [comment]
> Emacs 29.4 is a new stable release that needs to be added.

Thanks for the reminder. Please prefer opening new issues to bumping old ones in the future.

**Comment by panchoh** [comment]
> Any body having the same issue in the latest emacs?

Way ahead of you 😜 (#479).

**Comment by ynty** [comment]
Will this issue affect me if I use the release version of Emacs on Nix?

It seems that elpaca can resolve `elpaca-core-date` based on the release version number here:

https://github.com/progfolio/elpaca/blob/e9cb7eef2d8539e362d87f0489ab9eed8e8732c4/elpaca.el#L1144-L1158

**Comment by Icy-Thought** [comment]
@ynty depends on what version of Emacs you are installing. If you are grabbing the nixpkgs latest Emacs package, then you should be fine. Otherwise (emacs-overlay) you have to set the core date manually.
