### ISSUE TITLE
[Support]: magit transient installed version (20240110) lower than min required 20240201

### ISSUE THREAD

**Issue by fislysandi** [progfolio/elpaca#283]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [X] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

0.7

### Operating System

mac os 

### Description

elpaca just outright refuses to install magit for some stupid reason, i wanted to make my own emacs config but this outright ruins it, I DONT KNOW HOW TO FIX IT. why cant i pin the packages to a stable version? why?

**Comment by progfolio** [comment]
> [x]  I am checking these without reading them.

Please read the  issue template next time.

>  I have checked the documentation (README, Wiki, docstrings, etc)

The error your seeing is explained here:

https://github.com/progfolio/elpaca/wiki/Warnings-and-Errors#unmet-dependency-version

>  I have searched previous issues to see if my question is a duplicate.

Please also see https://github.com/progfolio/elpaca/issues/219

> Elpaca Version
> 0.7

0.7 is the installer version.
The template asks for the output of `M-x elpaca-version`.
That will include more information which I'll need to help.
Please include the output of that command.

**Comment by fislysandi** [comment]
ok sure!

**Comment by progfolio** [comment]
Please prefer text over screenshots in the future.

Assuming `elpaca-use-package-mode` is enabled, the following declaration will install the latest version of transient:

```emacs-lisp
(use-package transient :ensure t)
```

Then magit should be able to install.

**Comment by progfolio** [comment]
> I'm getting something similar with `kubernetes` package on Elpaca 0.7  (but on Linux) too:

For future reference, the output of `M-x elpaca-version` is more useful than saying "Elpaca 0.7 on Linux". It will include all the specific information. 0.7 is just the installer script version. Please use the `elpaca-version` command's output when reporting issues.

> then in elpaca-log I get: > kubernetes failed magit-popup installed version (0)
> lower than min required 2.13.0 01.010429

This is due to the fact that magit's author refuses to maintain the Version information in the main elisp package header, and instead relies solely on git tags for versioning their packages. I've pointed out to them how this users who wish to build from the repository (it requires us to download a full version of the repository, rather than a shallow clone, which costs unnecessary storage space, bandwidth, and time), but they were unwilling to change anything on their end last we spoke. Hopefully they'll come around on it. In the meantime, Elpaca is flexible enough to work around that.

> I can also add ` (use-package magit-popup :ensure t)` above the kubernetes

That's pretty close to the solution. You'll want a full clone of the magit-popup repository.
e.g.

This will cause Elpaca to look at the latest git tag for version information.
There was a bug with the regexp used for that, too.
The following should work:

1. Add the above declaration for magit-popup to your init file. 

``` emacs-lisp
(use-package magit-popup :ensure (:depth nil))
```

2. Save your init file.
3. `M-x elpaca-pull` `elpaca` to upgrade Elpaca.
4. Once the upgrade is complete `M-x restart-emacs`.

**Comment by progfolio** [comment]
@fislysandi I'll consider this issue closed with the advice here: https://github.com/progfolio/elpaca/issues/283#issuecomment-2016703625

If you're still having issues, feel free to comment and we can continue troubleshooting.
