### ISSUE TITLE
[Bug/Support]:ORG Mode "void-function seq--count-successive"

### ISSUE THREAD

**Issue by domsch1988** [progfolio/elpaca#291]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 3c1699a HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
 of 2024-03-11, modified by Debian
git --version:  git version 2.39.2

### Operating System

Debian stable

### Description

My normal org setup just stopped working with this error:
`elpaca--activate-package: (void-function seq--count-successive)`
I'm not entirely sure why. When emacs is startet up, describe-function can find seq--count-successive. I also tried setting :after (seq) for org, which doesn't help. It's a bit weird since it was working fine this morning. I just set up mu4e, which i don't think should have anything to do with org and restarted.

My entire config can be found online here: https://gitlab.com/domsch1988/domacs

My org configuration looks a like this:
```
  (use-package org
    :config
    (cond
     ((memq window-system '(w32))
      (setq org-capture-templates
	    '(("t" "Todo" entry (file+headline "d:/03_Documents/02_Notes/task.org" "Tasks")
	       "* TODO %?\n  %i\n  %a")
	      ("n" "Quicknote" entry (file+headline "d:/03_Documents/02_Notes/notes.org" "Notes")
	       "* %?\n  %i\n  %a")
	      ("j" "Journal" entry (file+datetree  "d:/03_Documents/02_Notes/journal.org" "Journal")
	       "* %?\nEntered on %U\n  %i\n  %a")))
      )
     ((memq window-system '(pgtk))
      (setq org-capture-templates
	    '(("t" "Todo" entry (file+headline "~/Daten/03_Documents/02_Notes/tasks.org" "Tasks")
	       "* TODO %?\n  %i\n  %a")
	      ("n" "Quicknote" entry (file+headline "~/Daten/03_Documents/02_Notes/notes.org" "Notes")
	       "* %?\n  %i\n  %a")
	      ("j" "Journal" entry (file+datetree  "~/Daten/03_Documents/02_Notes/journal.org" "Journal")
	       "* %?\nEntered on %U\n  %i\n  %a")))
      )
     )
    (add-to-list 'org-structure-template-alist '("t" . "src elisp :tangle"))
    (add-to-list 'org-structure-template-alist '("ti" . "src elisp :tangle init.el"))
    (add-to-list 'org-structure-template-alist '("tm" . "src elisp :tangle domacs-modules/"))
    :custom-face
    (org-document-title ((t (:family ,dom/font-slab :height 400))))
    :bind
    ("C-c n c" . org-capture)
    )
```

Interestingly, org seems to load actually fine. I can edit my org file, get highlighting and all the org commands are available. Just the variables don't get set anymore.

**Comment by domsch1988** [comment]
Update:
It WAS indeed related to me setting up mu4e. Somehow mu4e loading before org caused this issue. adding `:after (org)` to my mu4e use-package statement fixed this. Not sure why, but oh well.

**Comment by progfolio** [comment]
I. Mmw s
-------- Original message --------From: domsch1988 ***@***.***> Date: 4/12/24  7:56 AM  (GMT-05:00) To: progfolio/elpaca ***@***.***> Cc: Subscribed ***@***.***> Subject: [progfolio/elpaca] [Bug/Support]:ORG Mode "void-function seq--count-uuosuccessive"  (Issue #291) 
Confirmation

 I have checked the documentation (README, Wiki, docstrings, etc)
 I am  checking these without reading them.
 I have searched previous issues to see if my question is a duplicate.

Elpaca Versioni
Elpaca 3c1699a HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
of 2024-03-11, modified by Debian
git --version:  git version 2.39.2
Operating System
Debian stable
Description
My normal org setup just stopped working with this error:
elpaca--activate-package: (void-function seq--count-successive)
I'm not entirely sure why. When emacs is startet up, describe-function can find seq--count-successive. I also tried setting :after (seq) for org, which doesn't help. It's a bit weird since it was working fine this morning. I just set up mu4e, which i don't think should have anything to do with org and restarted.
My entire config can be found online here: https://gitlab.com/Dom. sch1988/domacs
My org configuration looks a like this:
  (use-package org
    :config
    (cond
     ((memq window-system '(w32))
      (setq org-capture-templates
	    '(("t" "Todo" entry (file+headline "d:/03_Documents/02_Notes/task.org" "Tasks")
	       "* TODO %?\n  %i\n  %a")
	      ("n" "Quicknote" entry (file+headline "d:/03_Documents/02_Notes/notes.org" "Notes")
	       "* %?\n  %i\n  %a")
	      ("j" "Journal" entry (file+datetree  "d:/03_Documents/02_Notes/journal.org" "Journal")
	       "* %?\nEnteremd on %U\n  %i\n  %a")))
      )
     ((memq window-system '(pgtk))
      (setq org-capture-templates
	    '(("t" "Todo" entry (file+headline "~/Daten/03_Documents/02_Notes/tasks.org" "Tasks")
	       "* TODO %?\n  %i\n  %a")
	      ("n" "Quicknote" entry (file+headline "~/Daten/03_Documents/02_Notes/notes.org" "Notes")
	       "* %?\n  %i\n  %a")
	      ("j" "Journal" entry (file+datetree  "~/Daten/03_Documents/02_Notes/journal.org" "Journal")
	       "* %?\nEntered on %U\n  %i\n  %a")))
      )
     )
    (add-to-list 'org-structure-template-alist '("t" . "src elisp :tangle"))
    (add-to-list 'org-structure-template-alist '("ti" . "src elisp :tangle init.el"))
    (add-to-list 'org-structure-template-alist '("tm" . "src elisp :tangle domacs-modules/"))
    :custom-face
    (org-document-title ((t (:family ,dom/font-slab :height 400))))
    :bind
    ("C-c n c" . org-capture)
    )

Interestingly, org seems to load actually fine. I can edit my org file, get highlighting and all the org commands are available. Just the variables don't get set anymore.

**Comment by progfolio** [comment]
(Sorry for the pocket email earlier...apparently my phone was doing quite a bit of that the other day.)

If I had to guess, there's a load order issue due to mu4e-org or another, transitive, dependency the two share.

**Comment by justinbarclay** [comment]
This saved me. I ran into this same issue as well and adding an `:after org` fixed it.
