### ISSUE TITLE
[Support]: magit-section and git-commit update fail with magit pinned

### ISSUE THREAD

**Issue by brabalan** [progfolio/elpaca#307]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

```
Elpaca 42507fe HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.1 (build 1, aarch64-apple-darwin23.0.0, Carbon Version 170 AppKit 2487)
 of 2023-11-02
git --version:  git version 2.45.0
```

### Operating System

macos 14.4.1

### Description

I use the following recipe for magit:
```emacs-lisp
(use-package magit :ensure (:tag "v3.3.0" :pin t))
```
and when I run `elpaca-update-all`, I have a failure for both `git-commit` and `magit-section`, each time with the same reason:
```
  [2024-05-13 18:23:40] Fetching remotes
  [2024-05-13 18:23:40] $git fetch --all -v
  [2024-05-13 18:23:40]   POST git-upload-pack (377 bytes)
  [2024-05-13 18:23:41]   From https://github.com/magit/magit
  [2024-05-13 18:23:41]    = [up to date]      v3.3.0     -> v3.3.0
  [2024-05-13 18:23:41] Continued by: #[128 "\302\301\303\300\"\"\207" [("Remotes fetched" nil) elpaca--process-sentinel apply append] 6 "

(fn &rest ARGS2)"]
  [2024-05-13 18:23:41] Remotes fetched
  [2024-05-13 18:23:41] $git --no-pager log --reverse --since=2021-10-04 21:55:06 +0200 --pretty=%h %s (%ch) ..@{u}
  [2024-05-13 18:23:41]   fatal: HEAD does not point to a branch
  [2024-05-13 18:23:41] Subprocess error (see previous log entries)
```

What do I need to do to fix this?

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a bug report.


In order to reduce disk space and improve installation speed, Elpaca only downloads one copy of the repositories which host several packages. Pinning magit detaches the repository HEAD, but the other packages in that repository are not aware they're implicitly pinned. This leads to:

> [2024-05-13 18:23:41]   fatal: HEAD does not point to a branch

> What do I need to do to fix this?

You could manually `:pin` those, but that's not an ideal solution.
I've pushed a patch which should catch those cases. See the output of the following test case:



<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :ref "fix/implicit-pin"
  :init
  (elpaca (magit :tag "v3.3.0" :pin t :wait t))
  (elpaca-update-all t)
  (elpaca-wait)
  (princ (elpaca-log "pinned")))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>106b628 HEAD -> fix/implicit-pin, origin/fix/implicit-pin</td>
<tr><td>installer</td><td>0.7</td>
<tr><td>emacs</td><td>GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-05-14</td>
<tr><td>git</td><td>git version 2.45.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping files for loaddefs... 
  INFO     Scraping files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.BKKZa6/elpaca/repos/elpaca'...
Switched to a new branch 'fix/implicit-pin'
branch 'fix/implicit-pin' set up to track 'origin/fix/implicit-pin'.
Checking /tmp/elpaca.BKKZa6/elpaca/repos/elpaca...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/doc/init.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/doc/installer.el...
Checking /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/test/elpaca-test.el...
Compiling /tmp/elpaca.BKKZa6/elpaca/repos/elpaca/test/elpaca-tests.el...
Done (Total of 12 files compiled, 4 skipped in 4 directories)

Downloading MELPA recipes...
Downloading MELPA recipes...100%
Downloading NonGNU-devel ELPA...
Downloading GNU-devel ELPA...
Downloading NonGNU ELPA...
Downloading GNU ELPA...

magit                          pinned               Skipping pinned package                                                          11.348255
magit-section                  pinned               Skipping pinned package                                                          11.348303
git-commit                     pinned               Skipping pinned package                                                          11.348321
```
</details>

You can test by updating Elpaca via `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs`. Then an `elpaca-update-all` should succeed. Let me know if that works for you.

As a side note, I recommend `elpaca-fetch-all` over `elpaca-update-all`.
The former allows inspecting package changes prior to merging them.

**Comment by brabalan** [comment]
It works great, thanks a lot! And thank you as well for the reminder about `elpaca-fetch-all`.

**Comment by progfolio** [comment]
> It works great, thanks a lot! And thank you as well for the reminder about `elpaca-fetch-all`.

Glad to hear it. Thanks for testing!
