### ISSUE TITLE
[Bug/Support]: Cannot operate on orphans in elpaca-ui

### ISSUE THREAD

**Issue by dinkonin** [progfolio/elpaca#316]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca 8d9cbe5 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)
 of 2024-06-04
git --version:  git version 2.45.2

### Operating System

Archlinux

### Description

when using elpaca-ui to mark/delete orphans ("g o" then "m" or "d" ) i get this error (wrong-type-argument listp ...
heres a sample backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument listp interactive-align)
  elpaca-ui-current-package()
  elpaca-ui-mark(:region elpaca-merge elpaca-ui--ensure-installed advance)
  elpaca-ui-mark-merge()
  funcall-interactively(elpaca-ui-mark-merge)
  command-execute(elpaca-ui-mark-merge)
```

**Comment by progfolio** [comment]
> when using elpaca-ui to mark/delete orphans ("g o" then "m" or "d" ) i get this
> error (wrong-type-argument listp ... heres a sample backtrace: ``` Debugger
> entered--Lisp error: (wrong-type-argument listp interactive-align)
> elpaca-ui-current-package() elpaca-ui-mark(:region elpaca-merge
> elpaca-ui--ensure-installed advance) elpaca-ui-mark-merge()
> funcall-interactively(elpaca-ui-mark-merge)
> command-execute(elpaca-ui-mark-merge) ```

Thanks for the bug report.
I've pushed some changes which should improve the situation.
You may still run into cases where you can't use elpaca-delete to delete an orphan dir because it was installed under a different directory name than what Elpaca computes and that information is lost. In those cases, `elpaca-ui-visit` can be used to open `dired` and manually inspect/delete the directory.

Note that pressing "m" marks the package for merging by default, which will still signal a user-error ("package is not installed").

To test:

1. `M-x elpaca-update` `elpaca` 
2. `M-x restart-emacs` once the update finishes

Let me know if that works for you. Thanks.

**Comment by dinkonin** [comment]
It works perfectly, thank you.

**Comment by progfolio** [comment]
> It works perfectly, thank you.

Thanks for testing.
