### ISSUE TITLE
[Bug/Support]: M-x elpaca-version could be easier to use

### ISSUE THREAD

**Issue by matta** [progfolio/elpaca#322]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

See subject of issue, below.  ;-)

### Operating System

n/a

### Description

> Please include the output of the elpaca-version command (M-x elpaca-version)

The above instructions are difficult to comply with because `M-x elpaca-version` emits a multi-line string to the Message window. After the command runs it is not possible to switch to the minibuffer and copy the text, since it disappears. I'm an experienced Emacs user and know I can switch to the `*Messages*` window and scroll to the end to find it, but it would proably be more friendly if the version diagnostics were displayed in a new buffer, maybe created with `with-temp-buffer-window`.

**Comment by progfolio** [comment]
> After the command runs it is
> not possible to switch to the minibuffer and copy the text, since it disappears.

That's the echo area (vs minibuffer, which it is possible to copy text from).

> The above instructions are difficult to comply with

I've added a note that the info can be copied from `\*Messages*\` to the issue template rather than complicate the command. I think that's a fair amount of working Emacs knowledge to assume from users and avoids complicating the command.

Thanks for the suggestion.
