### ISSUE TITLE
[Bug/Support]: Repository not on Disk

### ISSUE THREAD

**Issue by TriAttack238** [progfolio/elpaca#356]
### Confirmation

- [X] I have checked the documentation (README, Wiki, docstrings, etc)
- [ ] I am  checking these without reading them.
- [X] I have searched previous issues to see if my question is a duplicate.

### Elpaca Version

Elpaca ac6f563 HEAD -> master, origin/master, origin/HEAD
installer:      0.7
emacs-version:  GNU Emacs 29.4 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2024-06-23
git --version:  git version 2.43.0
No other window to select

### Operating System

Ubuntu 24.04.1 LTS

### Description

When trying to update my packages on this device with `elpaca-update-all`, I found that some packages did not update, giving the message `subprocess failed (see previous log`. I tried to solve this problem by deleting the package Magit and trying to install it again, when I found that there are now new messages. When elpaca tries to install the package on startup it says: fatal: `Remote branch melpa not found in upstream origin`. Surely enough, trying to search MELPA with `elpaca-try` cannot find magit, even though I do not think that Magit has been removed from Melpa. When I try to `elpaca-update-all`, the minibuffer simply returns `Repository not on Disk`. So I think there might be some sort of problem where elpaca is failing to properly connect to Melpa.

**Comment by progfolio** [comment]
Thanks for taking the time to fill out a support ticket.

> When trying to update my packages on this device with `elpaca-update-all`, I
> found that some packages did not update, giving the message `subprocess failed
> (see previous log`.

In the future, please share those log entries (you can use `M-x elpaca-info` followed by the package name or by pressing `RET` in the UI buffer to see the full log for a single package).
It will help narrow down any issues.

> When elpaca tries to install the package on startup it says: fatal: `Remote
> branch melpa not found in upstream origin`.

The MELPA recipe for Magit was briefly changed, then fixed.

> Surely enough, trying to search
> MELPA with `elpaca-try` cannot find magit, even though I do not think that Magit
> has been removed from Melpa. When I try to `elpaca-update-all`, the minibuffer
> simply returns `Repository not on Disk`. So I think there might be some sort of
> problem where elpaca is failing to properly connect to Melpa.

The issue is likely that you have outdated MELPA recipes under cache/menu-items.eld.
Try:

1. `M-x elpaca-update-menus` and hit `RET` to update all menus
2. Ensure magit is deleted with `M-x elpaca-delete` `magit`. 
3. `M-x restart-emacs`. Elpaca should reinstall magit, inheriting from the most up to date MELPA recipe.

If you have any issues with magit's dependencies (which had similar MELPA recipe changes), follow step 2 for those as well.
Let me know if that helps.

**Comment by TriAttack238** [comment]
Thank you, your instructions worked beautifully. I will be sure to check the specific package logs next time. As future reference, you have to delete all packages thatuse a dependency in order to delete a dependency.
