### ISSUE TITLE
[Support]: avoiding `head does not point to a branch`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [progfolio/elpaca#36]
### Emacs Version

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)

### Operating System

OS: Guix System 371aa5777a3805a3886f3feea5f1960fe3fe4219 x86_64 

### question

How to avoid `head does not point to a branch` error when updating a package? I tried to update one of my packages `tempel` and the updating failed due to the before mentioned git error. When I visited the directory of the package I saw that it was not checkout out to a branch. And looking at my recipes I saw that there was no default branch. This is true even for packages I installed with `elpaca` after I started using it.

Should there be a default branch? 

If not, I figure I should programmatically add one for all of the recipes I have.

### Relevant information

```emacs-lisp
tempel                         update-log           fatal: HEAD does not point to a branch                                           53463.776085
```
```


### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
Please include the recipe for the package.

**Comment by Luis-Henriquez-Perez** [comment]
This is the recipe I use for tempel.

```
'(tempel :package "tempel" :repo "minad/tempel" :fetcher github :files ("*.el" "*.el.in" "dir" "*.info" "*.texi" "*.texinfo" "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo" "lisp/*.el" (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el" "LICENSE" "README*" "*-pkg.el")) :protocol https :remotes "origin" :inherit t :depth 1 :ref "b4bb7030e9fa4a9451b79dfb2e815e0dd796527d")
```

I generated my recipe from the write recipe file `elpaca-write-lockfile`. What is the expected behavior for elpaca--should `:branch' be in these recipes? Does it just assume `master` branch by default? If no `:branch` is provided is the default behavior to not point to any branch?

Another recipe I've noticed with this same issue.

```
'(auto-capitalize :protocol https :remotes "origin" :inherit t :depth 1 :fetcher github :repo "emacsmirror/auto-capitalize" :ref "0ee14c76d5771aaa84a004463f8b8b3a195c2fd8" :package "auto-capitalize" :files (:defaults))
```

And yet another:

```
'(dash :package "dash" :fetcher github :repo "magnars/dash.el" :files ("dash.el" "dash.texi") :protocol https :remotes "origin" :inherit t :depth 1 :ref "7a9c9378772b687a452966ce4745c54afb19a2fc")
```

**Comment by progfolio** [comment]
> Should there be a default branch?

Git doesn't really have a concept of a default branch.
That's more a convention with certain forges (e.g. github).

> should :branch be in these recipes?

Considering the `:ref` keyword can refer to any git ref, I would say not. Otherwise two different branch names could be referred to via `:ref` and `:branch`.

There are checks in `elpaca--checkout-ref` which guard against these types of combinations:

https://github.com/progfolio/elpaca/blob/b8863b006de036ae3f7341ea2e6c84a96c879797/elpaca.el#L1185-L1191

> Does it just assume master branch by default?

It currently defers to git's behavior, which is whatever the remote HEAD is pointing at. That is often, but not always, a "master" or "main" branch.

 > If no :branch is provided is the default behavior to not point to any branch?
 
 If neither `:branch`, `:tag`, or `:ref` are provided, then the remote HEAD is used.  The same outcome as running the command `git clone URL`. What's happening here is a specific commit is being checked out via `:ref`. That will run `git checkout commit` which will put the repository into a detached HEAD state.

I'm still working on the design of lockfile loading, but eventually `elpaca-load-lockfile` will load the lockfile's reicpes and properly checkout the commits in the file. That should lead to less of a need to specify a commit `:ref` directly in the recipe (it can be delegated to lockfiles).

What is also needed is a way to tell Elpaca "I want to reset the repository state (unless I'd lose work) to what my recipe specifies". That way a recipe can be altered during your Emacs session and then rebuilt pointing to a new commit. There are some complexities that need to be considered here, though, that I'm still working on. I plan on getting those worked out soon.

Keep in mind that once the repo state is set, you can manually change it however you like. Elpaca will not automatically reset the repo when Emacs is restarted (this is intentional, so one can develop elisp packages or apply patches without Elpaca stepping on their work). So pointing any of the packages you listed above to a branch which can be pulled (via magit, vc, or the command line) should then allow you to update them for now until the above system is fully implemented.

**Comment by Luis-Henriquez-Perez** [comment]
>  That should lead to less of a need to specify a commit :ref directly in the recipe (it can be delegated to lockfiles).

I have all my recipes in separate (org) file from my config. So I don't mind--in fact I like--having all the information about my packages in one place.

> What is also needed is a way to tell Elpaca "I want to reset the repository state (unless I'd lose work) to what my recipe specifies".

Agreed. I would also add that it would be useful to go both ways. For example, you change the reference of a package, rebuild the package and find that the update is safe and you like the new features. Then you can tell elpaca to change the corresponding commit in the lockfile to reflect the current one. This would be a subset of `elpaca-write-lockfiles`. Often you don't want to go all out with `elpaca-write-lockfiles` because you only want to change a few recipes.

> So pointing any of the packages you listed above to a branch which can be pulled (via magit, vc, or the command line) should then allow you to update them for now until the above system is fully implemented.

I'd really like to automate this.

The point I'm trying to make is that it just seems inconvenient to need to need to switch to a branch before updating a package. Right now I'd guess most of my packages are in this "branchless" state. I would prefer even specifying the branch in the recipes so that I wouldn't have to do the pointing myself. I'd like `elpaca` to just do what I mean.

Is the idea behind this that multiple branches could have the same commit and therefore we may not know which branch you'd like to update to?

**Comment by progfolio** [comment]
> Often you don't want to go all out with elpaca-write-lockfile because you only want to change a few recipes.

I don't think I'll go the route of programmatically trying to update lockfiles on disk in place. That's much more complicated than just writing to a new file. Bear in mind that, if no other refs have changed, and you write to the same file, it will be "updated" on disk by overwriting the previous version.

> I'd really like to automate this.

The lockfile system will handle most of this.
I'll still have to think about how to handle the use case you're describing (commits declared in each recipe, with Elpaca deducing the proper branch to update). But I've noted it down and will think on it.

>  Right now I'd guess most of my packages are in this "branchless" state.

That is how git works when a commit is checked out directly. The HEAD is detached at that point.

> I would prefer even specifying the branch in the recipes so that I wouldn't have to do the pointing myself. I'd like elpaca to just do what I mean.

The problem is coming up with a generalized solution.
"Do what I mean" means different things to different people.

> Is the idea behind this that multiple branches could have the same commit and therefore we may not know which branch you'd like to update to?

That's one case. There are others. e.g. What reference should be initially checked out? I'd like to avoid creating a precedence for each of these recipe keywords that changes depending on the command being issued. That will get confusing quickly.

>  I like having all the information about my packages in one place.

That's essentially what the lockfile will be: a collection of the fully computed recipes based off of your init file's declarations and inheritied data, unless disabled, that has been added via `elpaca-order-functions`, `elpaca-recipe-functions`, and any corresponding menu item in `elpaca-menu-functions`.

I plan on working on some of this tonight. I'll keep you posted.
