### ISSUE TITLE
[Feature]: Display package's readme in package information

### ISSUE THREAD

**Issue by jumper047** [progfolio/elpaca#373]
### Feature Description

Package.el `list-packages` command's buffer displays packages readme on pressing enter. Is it possible to add this information in elpaca-manager's package details window?

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
> ### Feature Description
> 
> Package.el `list-packages` command's buffer displays packages readme on pressing
> enter. Is it possible to add this information in elpaca-manager's package
> details window?

Thanks for the feature suggestion.
I've added `elpaca-info-sections-hook`, which could be customized to display a package's README inline in the info buffer. There's also a convenience macro, `elpaca-info-defsection` for defining new section functions. For example, the following will use the pandoc command line tool to insert a plain text version of a package's README file if it is locally on disk: 

``` emacs-lisp
(elpaca-info-defsection readme
  (let-alist elpaca-info-alist
    (when-let* ((.e)
                (repo (elpaca<-repo-dir .e))
                (default-directory repo)
                (readme (car (directory-files-recursively default-directory
                                                          "(README\\|readme"))))
      (let ((from (alist-get (file-name-extension readme)
                             '(("md" . "markdown")
                               ("org" . "org"))
                             nil nil #'equal)))
        (with-temp-buffer
          (insert-file-contents readme)
          (shell-command-on-region
           (point-min) (point-max)
           (concat "pandoc --quiet "  (when from (format "-f %s " from)) "-t plain") nil t)
          (concat "\n" (buffer-string) "\n"))))))

(cl-pushnew #'elpaca-info-section--readme (nthcdr 1 elpaca-info-sections-hook))

```

The situation is a little more complex than what package.el offers, because Elpaca can pull recipes from more than just ELPAs. So I don't think I'll be adding anything like this to Elpaca by default. Also, the README is available for browsing locally via `elpaca-visit` and usually available on the Internet via `elpaca-browse`, too. 

Other such functions can be written to scrape the README info from the package's website or, more generally, display whatever one wishes in the `elpaca-info` buffer.

Does that help?

**Comment by progfolio** [comment]
I'll consider this closed for now.
