### ISSUE TITLE
[Bug]: elpaca-use-package macro with quote expands to (use-package quote)

### ISSUE THREAD

**Issue by Riyyi** [progfolio/elpaca#45]
### Emacs Version

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

### Operating System

Arch Linux x86_64 on kernel 6.0.10-arch2-1

### Bug Description

The current `elpaca-use-package` macro seems to only work with a list.

```emacs-lisp
(elpaca-use-package 'which-key)
;; expands to
(elpaca 'which-key
  (use-package quote))
```

```emacs-lisp
(elpaca-use-package (which-key))
;; expands to
(elpaca
    (which-key)
  (use-package which-key))
```

I don't know if both variants are desired, but under the quick start section of `/README.org` the quote variant is used.
In the `/doc/manual.org` document under the "Installing Packages" section the list variant is used.

**Comment by progfolio** [comment]
Thank you for the bug report.
I've patched `elpaca-use-package` so that it can tolerate quoted/backquoted forms.
I've also dropped the unnecessary quotes from the macro examples in the documentation (they were outdated).
You should be able to update via `M-x elpaca-update elpaca` followed by restarting Emacs.
Testing is appreciated.

**Comment by Riyyi** [comment]
>Testing is appreciated.
I tested the patch unquoted, quoted and in a list, all three form work now. Thank you.
