### ISSUE TITLE
[Support]:  should elpaca modify `initial-buffer-choice`?

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [progfolio/elpaca#52]
### Emacs Version

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-09-12

### Operating System

Arch Linux x86_64 

### question

I want to argue that elpaca should not modify the variable`initial-buffer-choice` and that that variable should be reserved exclusively for user modification.

I understand that when something goes wrong it can be convenient to show elpaca log. 

One of my concerns that the indirection caused by elpaca's setting of `initial-buffer-choice` only to switch to the user's `initial-buffer-choice` is a source of unexpected behaviors. If some error occurs between elpaca's setting of `initial-buffer-choice` and the user setting it himself, or if the user's configuration has some code assumes (as it should be able to) that relies `initial-buffer-choice`'s value never changes something unexpected may happen.

Arguably, even if this doesn't happen the user may not want `*elpaca-log*` or any other elpaca buffer to be the initial buffer even if something goes wrong with elpaca.

Furthermore, elpaca's manipulation of `initial-buffer-choice` means that it is more involved for the user to customize elpaca's default behavior on which buffer to show under which circumstances because in addition to writing his own function to add into `initial-buffer-choice` he has to then suppress elpaca from trying to do so itself.

I propose that elpaca instead provides a function that the user can add into `initial-buffer-choice` which would provide elpaca's behavior as to which buffer and in what circumstance to display it and would default to the user's value for `initial-buffer-choice`. 

This way the user can add it in their bootstrap code easily if they wish (maybe it should be in the bootstrap code by default) but it is not imposed on them.

```elisp
(setq initial-buffer-choice #'elpaca-default-elpaca-buffer-maybe)
```
The function `elpaca-default-elpaca-buffer-maybe` could optional take a user's `initial-buffer-choice` value to default to.

### Confirmation

- [X] I've read the documentation and I still am unsure.

**Comment by progfolio** [comment]
Does `(setq elpaca-hide-initial-build t)` not work as expected?

**Comment by progfolio** [comment]
>  It is question of design. I'm not sure if elpaca should be responsible for displaying an elpaca buffer using the variable initial-buffer-choice since that's meant for user customization. Surely it can create the buffer. And possibly even display it via display-buffer. But I'm wary about using initial-buffer-choice for that.

The design goal is to display the build buffer (unless the user explicitly says they don't want to) when Elpaca must build packages on installation. I made this the default behavior because it can be confusing to fire Emacs up and not know packages are building in the background.

I'm in favor avoiding modifications of initial-buffer-choice to accomplish this.

> Surely it can create the buffer. And possibly even display it via display-buffer

At one point I tried this approach. The need to build is detected while packages are being queued, before the initial-buffer-choice has been displayed. So displaying the buffer then was not enough, as initial-buffer-choice would override it. This could be mitigated by adding to `emacs-startup-hook`, but then we're modifying another user option.

> [dashboard](https://github.com/emacs-dashboard/emacs-dashboard) leaves it to the user to set their initial buffer choice even though the package's primary purpose is to display the dashboard as the initial buffer.

I'd rather not require the user to do that in this case.

I'll take another look at solving this problem without using initial-buffer-choice once I get more pressing features worked out. If the current version causes any problems, please let me know.
