### ISSUE TITLE
[Support]: Setup.el

### ISSUE THREAD

**Issue by Cloudcolour** [progfolio/elpaca#68]
### Elpaca Version
```
Elpaca 0ccd8eb HEAD -> master, origin/master, origin/HEAD
installer:      0.1
emacs-version:  GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-24
git --version:  git version 2.39.1
```
### Operating System

Arch-linux

### Question

This isn't a bug, exactly. I am using `elpaca` with `setup.el` and am attempting to define a keyword for using `elpaca` in a `setup.el` using its mechanisms. I would consult with the creator/maintainer of `setup.el` but last I read he was on a hiatus from that role. I looked at https://github.com/progfolio/elpaca/issues/58 but it didn't appear to directly address my problem. I would appreciate it if you could suggest how I might proceed. 

My initial definition is the following:
```lisp
(setup-define :elpaca
   (lambda (recipe)
     `(unless (elpaca ',recipe)
        ,(setup-quit)))
   :documentation
   "Install RECIPE with `elpaca'.
This macro can be used as HEAD, and will replace itself with the
first REIPCE's package."
   :repeatable t
   :shorthand (lambda (sexp)
                (let ((recipe (cadr sexp)))
                  (if (consp recipe)
                      (car recipe)
                    recipe))))
```
This is how I would define it for `straight.el`. However, `elpaca` is asynchronous. So I need to ensure that other keywords which depend on a package being installed only  execute after `elpaca` installation completes for that package. 

Otherwise, something like
```lisp
(setup (:elpaca vertico)
  (vertico-mode +1))
```
Will not work properly because `setup` is attempting to activate `vertico-mode` before it's installed. A solution like incorporating `elpaca-wait` into my macro would fix this particular problem, but I would lose the advantages of asynchronous installation.

How did address this problem with respect to `use-package` with your `elpaca-use-package` extension? I looked at it the code, but how you are accounting for this particular issue is opaque to me. Can you shine some light on this?

**Comment by progfolio** [comment]
> Will not work properly because setup is attempting to activate vertico-mode before it's installed. 

The goal would be to expand so that the configuration portion of the code happens in the BODY of an elpaca call. e.g.

```emacs-lisp
(setup (:elpaca vertico)
  (vertico-mode +1))
  
  ;; should expand to
  
  (elpaca vertico (vertico-mode +1))
  ```
  
> A solution like incorporating elpaca-wait into my macro would fix this particular problem, but I would lose the advantages of asynchronous installation.

I agree that's not a solution. `elpaca-wait` should be used sparingly and only when necessary.

> How did address this problem with respect to use-package with your elpaca-use-package extension? I looked at it the code, but how you are accounting for this particular issue is opaque to me. Can you shine some light on this?

The expansion works similar to the example I gave above. e.g.

```emacs-lisp
(use-package test :config (config))

;;expands to:

(elpaca test
  (require 'test nil nil)
  (config)
  t)
```
In use-package there is a list which stores the keywords and the order in which they are processed. I registered the `:elpaca` keyword in the appropriate place so that it is processed before many of the other keywords. It wraps the rest of what use-package would normally do in the `elpaca` macro call. 

> I would consult with the creator/maintainer of setup.el but last I read he was on a hiatus from that role. I looked at https://github.com/progfolio/elpaca/issues/58 but it didn't appear to directly address my problem. I would appreciate it if you could suggest how I might proceed.

If you're unable to figure it out, I would suggest finding someone who is familiar with setup.el and comfortable writing elisp. It doesn't have to be the maintainer (which, if the project has no current maintainer as you mention, I would try and get that sorted or re-evaluate relying on it first). I suggested that, because they would probably be the most familiar with setup.el's internals. I don't plan on using setup.el, so I'm not the right person for that job.
