### ISSUE TITLE
[Feature]: elpaca-use-package: keyword to ignore built-in packages

### ISSUE THREAD

**Issue by progfolio** [progfolio/elpaca#73]
### Feature Description

Rather than adding a recipe keyword, the elpaca-use-pcakage keyword could accept a symbol which indicates that the user wants the package added to elpaca-ignored-dependencies. e.g.

```emacs-lisp
(use-package pre-installed :elpaca ignore)
;; expands to:
(progn
  (cl-pushnew 'pre-installed elpaca-ignored-dependencies)
  ;;use-package expansion
  (require 'pre-installed nil nil))
```

Mentioned here: https://www.reddit.com/r/emacs/comments/11daqsz/elpaca_the_basics/jabl46k/
Related: #66

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by benide** [comment]
Following up from Reddit. I suggested having something like `:elpaca ignore-maybe` which would check if the package is already available and if so add it to `elpaca-ignore-dependencies`, and if not then install with elpaca.

The use case for me is that I have Emacs installed in two places, one is a NixOS system and the other is not, and I only have extra pre-installed packages on the NixOS system. I do that so that things like `vterm` compile via Nix. I'd like to use an identical config for both systems. (I already use the same config on both, but with my own macro to accomplish this)

I'll include the idea here, a bit more correct (I think) than what I put on reddit:

```elisp
(use-package maybe-pre-installed :elpaca ignore-maybe)
;; expands to:
(if (locate-library (symbol-name 'maybe-pre-installed))
    (progn
      ;; use-package expansion as if :elpaca nil
      (cl-pushnew 'pre-installed elpaca-ignored-dependencies))
  (progn
    ;; use-package expansion as if :elpaca t
    ))
```

Hopefully that makes sense. If you think this doesn't belong in elpaca, that's totally fine :)

**Comment by progfolio** [comment]
After more consideration, I feel like this use-case is pretty rare.
If similar requests crop up, I'll consider adding something like this.
