### ISSUE TITLE
[Feature]: report  package load/confirugration times

### ISSUE THREAD

**Issue by actondev** [progfolio/elpaca#89]
### Feature Description

I just tried using elpaca instead of use-package, and was surprised how in total it takes more time to get emacs show with the configured theme etc.
With use-package I have something around `1.4s`  (as reported by `emacs-init-time`, and I assume that includes all the `:config` steps as they are done synchronously).
With elpaca `emacs-init-time` reports roughly `1s`, but then to load the packages I want at startup (theme, dashboard, completion etc) it seems that it needs around that much more to load the packages.

A nice feature of use-package is that it reports times, such as
```
Configuring package dashboard...done
Loading package dashboard...done (0.059s)
Loading package doom-themes...
Configuring package doom-themes...done (0.043s)
```

Meanwhile in `elpaca-status` shows only the package clone/getting dependencies & parsing the autoloads. I think a timing page of the `:configure` steps for packages would be useful as well.

Apologies if I'm saying something just wrong here.

### Confirmation

- [X] The feature I'm proposing does not already exist in Elpaca

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a request.

> I just tried using Elpaca instead of use-package

Just to be clear, use-package is not a package manager. It is a configuration macro which optionally integrates with package managers (package.el, straight.el, Elpaca, etc).

> I [...] was surprised how in total it takes more time to get emacs show with the configured theme etc.

I'd be happy to take a look at your init files if you have them uploaded anywhere.
I may be able to give you advice on how to speed things up.

> as reported by emacs-init-time

emacs-init-time measures the difference between after-init-time and before-init-time. 
Depending on your setup with Elpaca, that's going to be lower because after-init-time is set prior to the package queues being processed. A more accurate way of measuring the init time would be to add something like the following to `elpac-after-init-hook' prior to processing queues:

```emacs-lisp
(add-hook 'elpaca-after-init-hook
          (lambda ()
            (message "Emacs loaded in %s with %d garbage collections."
                    (format "%.2f seconds"
                             (float-time (time-subtract (current-time) before-init-time)))
                     gcs-done)))
```

I would start by adding that and seeing what time it reports.

> I assume that includes all the [use-package] :config steps as they are done synchronously

Hard to say without seeing the actual declarations. There are lots of use-package keywords which defer loading packages


As far as adding something like that to Elpaca, I'll have to think on it.
Package configuration is separate from package management, so I'm not sure measuring configuration time is the responsibility of a package manager.
It may be better left to a configuration macro, such as use-package.

**Comment by actondev** [comment]
I realized that elpaca use-package acts just as a wrapper around use-package, so the following configuration
``` emacs-lisp
(setq use-package-always-ensure t
      use-package-always-defer t
      use-package-verbose 'verbose
      use-package-minimum-reported-time 0.01)
```
just works.
I can indeed still see `:config` times such as `Configuring package doom-themes...done (0.043s)`.
Thus I will close the issue.

Also the init times comparison I mentioned (where elpaca felt slower) was apples with orange, since I was using emacs 29 for elpaca (cause of the --init-directory flag support), vs emacs 28.2 for my previoius setup.
Comparing both setups with emacs 29, elpaca feels just as fast (if not faster). Not to mention the big difference in startup when starting from scratch without any package downloaded! 

Thanks a lot for this package and for your time!

**Comment by progfolio** [comment]
> The following configuration just works

I do something similar in my init file, but I condition it on whether or not debug-on-error is non-nil:

```emacs-lisp
(if debug-on-error
    (setq use-package-verbose t
          use-package-expand-minimally nil
          use-package-compute-statistics t)
  (setq use-package-verbose nil
        use-package-expand-minimally t))
```

> Comparing both setups with emacs 29, elpaca feels just as fast (if not faster). Not to mention the big difference in startup when starting from scratch without any package downloaded!

Glad to hear it.


> Thanks a lot for this package and for your time!

Thank you for trying it out and the feedback!
